version: '3.7'

services:
  application:
    image: openjdk:15-jdk-slim
    working_dir: '/app'
    volumes:
      - "./build/libs:/app"
    entrypoint: [ 'java' ,'-jar', '-Duser.timezone=UTC' ,'app.jar' ]
    environment:
      - SPRING_PROFILES_ACTIVE=pro
  proxy:
    image: nginx:1.15
    depends_on:
      - application
    volumes:
      - './docker/nginx:/etc/nginx/conf.d:ro'
      - './docker/ssl:/etc/ssl:ro'
    ports:
      - '80:80'
      - '443:443'
  database:
    image: postgres:13.1-alpine
    volumes:
      - './.docker/postgres/etc:/etc/postgresql'
      - './.docker/postgres/log:/var/log/postgresql'
      - './.docker/postgres/data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: basic
      POSTGRES_PASSWORD: 9HHPU4Xur2KzewASuSbpkv
      POSTGRES_DB: main
