server:
  port: 8080
pebble:
  cache: true
spring:
  web:
    resources:
      chain:
        enabled: true
        cache: true
      add-mappings: true
      cache:
        cachecontrol:
          max-age: 365d
  r2dbc:
    url: 'r2dbc:postgresql://127.0.0.1:5432/main'
    username: basic
    password: 9HHPU4Xur2KzewASuSbpkv

application:
  ads:
    pictures:
      path: '/application/uploads/ads/'
